### ISSUE TITLE
Clean outputs of pymialsrtk

### ISSUE THREAD

**Issue by t-sanchez** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#150]
The outputs of pymialsrtk contain by default too much material.

There should be a default setting that returns a minimal set of outputs, such as the SR reconstruction and its json, the brain mask, as well as labelmaps (#133). The rest should be optional outputs.

In addition,
- `_reduceFOV` folders should be removed.
- reports should contain run_ids

**Comment by t-sanchez** [comment]
In addition, with options to do multiple runs of preprocessing or sr, the output in pymialsrtk is overwritten partially. 

We should think of a way of handling it more cleanly.

**Comment by t-sanchez** [comment]
In addition, we should use a BIDS-compliant formatting without using `sr` as a tag, but rather use `desc-`.

**Comment by pdedumast** [comment]
Not exhaustive, TBC:

- [ ] Remove addition of pre/post fix in filename from many interfaces.
- [ ] Define clear BIDS compliant output filenames
- [ ] Define minimalist default outputs (SR image, SR mask, SR json, report + eventual custom_interfaces outputs : SR labels, CSV metrics files). Output all files (e.g. all preprocessed LR images) only on request
- [ ] Manage multi_parameters custom interface and run ids

**Comment by pdedumast** [comment]
See #184 and #185
