### ISSUE TITLE
ENH: add more options to control/skip intensity standardization

### ISSUE THREAD

**Issue by sebastientourbier** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#72]

**Comment by pdedumast** [comment]
@sebastientourbier @helenelajous Did you figure out which modules are finally concerned? Can you tell me exactly based on [this graph](https://mialsrtk.readthedocs.io/en/latest/_images/nipype_wf_graph.png) please

**Comment by sebastientourbier** [comment]
@pdedumast We wanted to make a short meeting all together with @helenelajous to discuss this.
I am available now in case.
