### ISSUE TITLE
DOC: Make sure the references to version TAG are correct

### ISSUE THREAD

**Issue by helenelajous** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#78]
In the documentation, 'v' is missing in the command line to get the latest release (2.0.1) of the BIDS App:
$ docker pull sebastientourbier/mialsuperresolutiontoolkit:**v**2.0.1
Probably missing as well in the singularity pull.

**Comment by sebastientourbier** [comment]
Thanks @helenelajous !
Indeed this should have been already fixed in the current PR #70 and it will come when we merge it.
The updated documentation for this PR is rendered at the following URL:
https://mialsrtk.readthedocs.io/en/v2.0.2-dev/index.html

**Comment by sebastientourbier** [comment]
Seems there is something wrong in rendering the release number thought...

**Comment by sebastientourbier** [comment]
All fixed by PR #79
