### ISSUE TITLE
BUG: "skip_stacks_ordering" option doesn't work

### ISSUE THREAD

**Issue by helenelajous** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#82]
When I want to keep the order of stacks specified in "stacks" (i.e., "custom_inferfaces": {"skip_stacks_ordering": true}), the stacksOrdering function is still performed. The final SR recon doesn't take into account the stack order I specified.

**Comment by helenelajous** [comment]
I had trouble applying the skip_stacks_ordering option due to:
1) a misuse of the pipeline - no error is reported if other variable names are used in the participants_params.json;
2) cached data.

**Comment by sebastientourbier** [comment]
@pdedumast In relation to last comment by @helenelajous what would you think about we use jsonschema (https://json-schema.org/) to validate the config file?
