### ISSUE TITLE
ENH: Improvement of the stacksOrdering 

### ISSUE THREAD

**Issue by helenelajous** [Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit#86]
Using the information on the number of rejected slices (in practice, number of NaN obtained from the motion index computation) in manual masks to penalize a stack in the optional stacks_ordering interface taking into account motion-related intensity artifacts like signal dropouts.

**Comment by sebastientourbier** [comment]
Following your suggestion, the proportion of nans has been computed in the StackOrdering interface e.g.:
https://github.com/Medical-Image-Analysis-Laboratory/mialsuperresolutiontoolkit/blob/e5626f6e8002eb7fc97ef0fd1377e896ec365658/pymialsrtk/interfaces/preprocess.py#L863
